# Change these first
owner: kitkatfund # Your GitHub organization or username, where this repository lives
repo: kitkatfund.github.io # The name of this repository

sites:
  - name: KitKat 
    url: https://www.kitkat.zone
  - name: KitKat Explorer
    url: https://explorer.kitkat.zone
  - name: KitKat Docs
    url: https://docs.kitkat.zone
  - name: Archway API
    url: https://archway-api.kitkat.zone/cosmos/auth/v1beta1/params
  - name: Archway RPC
    url: https://archway-rpc.kitkat.zone
  - name: BitCanna API
    url: https://bitcanna-api.kitkat.zone/cosmos/auth/v1beta1/params
  - name: BitCanna RPC
    url: https://bitcanna-rpc.kitkat.zone
  - name: Omniflix API
    url: https://omniflix-api.kitkat.zone/cosmos/auth/v1beta1/params
  - name: Omniflix RPC
    url: https://omniflix-rpc.kitkat.zone
  - name: Quasar API
    url: https://quasar-api.kitkat.zone/cosmos/auth/v1beta1/params
  - name: Quasar RPC
    url: https://quasar-rpc.kitkat.zone
  - name: Quicksilver API
    url: https://quicksilver-api.kitkat.zone/cosmos/auth/v1beta1/params
  - name: Quicksilver RPC
    url: https://quicksilver-rpc.kitkat.zone


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kitkat.zone
  # baseUrl: /kitkatfund.github.io
  logoUrl: https://raw.githubusercontent.com/kitkatfund/kitkat-assets/main/kitkat-logo-light.ico
  name: KitKat Services Status
  favicon: https://raw.githubusercontent.com/kitkatfund/kitkat-assets/main/kitkat-logo-light.ico
  introTitle: "KitKat Services Status"
  introMessage: The uptime status and history of all chain infra nodes hosted by KitKat can be found here.
  navbar:
    - title: Home
      href: https://www.kitkat.zone
    - title: Explorer
      href: https://explorer.kitkat.zone
    - title: Docs
      href: https://docs.kitkat.zone
    - title: Status
      href: /
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
